### ISSUE TITLE
Handle "not found" case with a clearer error

### ISSUE THREAD

**Issue by AnesHamdani08** [Zastai/MetaBrainz.MusicBrainz.CoverArt#41]
My app uses your libraries for auto-tagging (both MusicBrainz, and MusicBrainz.CoverArt, wonderful library by the way), however i ran into an issue where i only need the link to the cover, i don't want to download it. looking at the library there is only `Fetch` methods which downloads the data. This is working perfectly fine in auto-tagging but I need to supply URL to parts of the app that does the downloading on demand and manually and sometimes hand off the URL to another libraries. Is there a way to get the cover URL instead of only downloading it.

**Comment by Zastai** [comment]
You can use `FetchRelease` to get the release metadata. This includes information about all images associated with the release, including the URIs of both the originally uploaded image and any thumbnails generated by the CAA.

**Comment by AnesHamdani08** [comment]
This GUID:968db8b7-c519-43e5-bb45-9f244c92b670 , doesn't have an associated cover, the library attempts to parse and throws an exception, is there a way to check if cover is available instead of a Try/Catch block ?

```
System.Text.Json.JsonException
  HResult=0x80131500
  Message='<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at MetaBrainz.Common.Json.JsonUtils.<GetJsonContentAsync>d__7`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MetaBrainz.MusicBrainz.CoverArt.CoverArt.<FetchReleaseAsync>d__83.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MetaBrainz.Common.AsyncUtils.ResultOf[T](Task`1 task)
   at MetaBrainz.MusicBrainz.CoverArt.CoverArt.FetchRelease(Guid mbid)
   at QuickBeat.Dialogs.TagEditor.VB$StateMachine_21_Commands_Fetch_Executed.MoveNext() in C:\Users\AnesH\source\repos\QuickBeat\QuickBeat\Windows\Dialogs\TagEditor.xaml.vb:line 210

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

```

**Comment by Zastai** [comment]
Interesting. https://coverartarchive.org/release/968db8b7-c519-43e5-bb45-9f244c92b670 returns a 404, with html content, which is of course not valid JSON.

Looks like I never bothered to add proper error checking in this library (the ListenBrainz library would throw a nicer exception for this).

I may look at adding a `ReleaseExists()`, but then that would fetch the result just to discard it; perhaps a `FetchReleaseIfAvailable()`, which returns `null` for a 404, would make more sense.
`FetchRelease()` would then remain as a version that never returns `null` but would throw a NotFoundException() or similar.

**Comment by Zastai** [comment]
Interestingly, the current method docs say you should get a `WebException` in case of a 404 or 503. It looks like I never adjusted the error handling when I switched from `WebRequest` to `HttpClient`.
